### ISSUE TITLE
Where for _refreshCompleter to complete when pulling to refresh?

### ISSUE THREAD

**Issue by Jessense** [alefcarlos/colecao_bolso_app#6]
In the file `colecao_bolso_app/lib/src/collections/collections_list.dart`:
``` dart
  Future<void> _refreshData() {
    widget._collectionsBloc.dispatch(CollectionsFetchEvent());
    return _refreshCompleter.future;
  }
```
But I can't find where the _refreshCompleter complete. Won't the indicator keep loading? I am struggling with implement pull to refresh with bloc pattern but can't find a solution. I want to know how do you implement it?

**Comment by alefcarlos** [comment]
Hello,
In the `build` method you need to call

```dart
_refreshCompleter?.complete();
refreshCompleter = Completer()
```
The second line guarantees the a new instance is created when the data is loaded(or an error occurred).

On line 41 in this file:
https://github.com/alefcarlos/colecao_bolso_app/blob/master/lib/src/collections/collections_list.dart

**Comment by Jessense** [comment]
@alefcarlos Thanks for your solution! It worked!

**Comment by alefcarlos** [comment]
That's good ! You're welcome !
